project:
  type: book

book:
  title: "Embedded C Programming Lab Manual"
  author: "Livin Nector D"
  date: "9/18/2024"
  chapters:
    - index.qmd
    - exercises.qmd
    - part: "**Using STMCube IDE with STM HAL**"
      chapters:
        - exercises/1_uart.md
        - exercises/2_gpio.md
    - part: arduino_ide_with_stm32duino.qmd
      chapters: 
        - exercises/3_ultrasonic_sensor.md
        - exercises/4_temperature_sensor_i2c.md
        - exercises/5_accelgyro_i2c.md

    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo


website: 
  favicon: logo.ico
